//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AXMSwiftWS_4._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPOSITO_PME
    {
        public int operacion { get; set; }
        public string centro_regional { get; set; }
        public string nombre_centro_regional { get; set; }
        public string plaza { get; set; }
        public string nombre_plaza { get; set; }
        public string sucursal { get; set; }
        public string nombre_sucursal { get; set; }
        public Nullable<int> referencia { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
        public string causa { get; set; }
    
        public virtual OPERACION OPERACION1 { get; set; }
    }
}
