//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AXMSwiftWS_4._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERACION_DEFINIDA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPERACION_DEFINIDA()
        {
            this.OPERACION = new HashSet<OPERACION>();
        }
    
        public short operacion_definida1 { get; set; }
        public string descripcion_operacion_definida { get; set; }
        public short producto { get; set; }
        public string descripcion_kapiti { get; set; }
        public string code_kapiti_cliente { get; set; }
        public string code_kapiti_banco { get; set; }
        public string cuenta_kapiti_banco { get; set; }
        public string sufijo_kapiti_banco { get; set; }
        public Nullable<short> operacion_definida_global { get; set; }
        public Nullable<byte> agencia { get; set; }
        public Nullable<byte> tipo_operacion { get; set; }
        public string descripcion_interfaz_ced { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPERACION> OPERACION { get; set; }
    }
}
