//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AXMSwiftWS_4._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERACION_PIU
    {
        public int operacion { get; set; }
        public int operacion_piu1 { get; set; }
        public System.DateTime fecha_operacion { get; set; }
    
        public virtual OPERACION OPERACION1 { get; set; }
    }
}
