//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AXMSwiftWS_4._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERACION_SWIFT
    {
        public int no_rep_swift { get; set; }
        public int operacion { get; set; }
        public Nullable<System.DateTime> hora_envio { get; set; }
        public Nullable<int> numero_reporte_202 { get; set; }
    
        public virtual OPERACION OPERACION1 { get; set; }
    }
}
