//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AXMSwiftWS_4._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETRIZACION
    {
        public short parametro { get; set; }
        public string valor { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
        public string unidad_banca { get; set; }
    }
}
