//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AXMSwiftWS_4._0.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TICKETEntities : DbContext
    {
        public TICKETEntities()
            : base("name=TICKETEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEPOSITO> DEPOSITO { get; set; }
        public virtual DbSet<DEPOSITO_CED> DEPOSITO_CED { get; set; }
        public virtual DbSet<DEPOSITO_DIRECTO> DEPOSITO_DIRECTO { get; set; }
        public virtual DbSet<DEPOSITO_PME> DEPOSITO_PME { get; set; }
        public virtual DbSet<OPERACION> OPERACION { get; set; }
        public virtual DbSet<OPERACION_DEFINIDA> OPERACION_DEFINIDA { get; set; }
        public virtual DbSet<OPERACION_PIU> OPERACION_PIU { get; set; }
        public virtual DbSet<OPERACION_SWIFT> OPERACION_SWIFT { get; set; }
        public virtual DbSet<PARAMETRIZACION> PARAMETRIZACION { get; set; }
    
        public virtual ObjectResult<sp_piu_gen_retiro_MT103_Result> sp_piu_gen_retiro_MT103(string lsNumero_Movimiento, string lsB1_Indentificador, string lsB1_Identificador_Aplic, string lsB1_Identificador_Serv, string lsB1_Direccion_Swift, string lsB1_Ind_Aplicacion, string lsB1_Branch_Code, string lsB2_Identificador, string lsB2_Identificador_io, string lsB2_Tipo_Mensaje, string lsB2_Direccion_Swift, string lsB2_Ind_Aplicacion, string lsB2_Branch_Code, string lsB2_Prioridad, string lsB3_Identificador, string lsB3_Tipo_Mensaje, string lsB3_Texto, string lsB4_Identificador, string lsB4_Campo_20, string lsB4_Campo_23b, string lsB4_Campo_32a_Fecha, string lsB4_Campo_32a_Moneda, string lsB4_Campo_32a_Monto, string lsB4_Campo_50k_Cuenta, string lsB4_Campo_50k_Direc1, string lsB4_Campo_50k_Direc2, string lsB4_Campo_50k_Direc3, string lsB4_Campo_50k_Direc4, string lsB4_Campo_53d_Opt1, string lsB4_Campo_53d_Opt2, string lsB4_Campo_53d_Desc1, string lsB4_Campo_53d_Desc2, string lsB4_Campo_53d_Desc3, string lsB4_Campo_53d_Desc4, string lsB4_Campo_56d_Opt1, string lsB4_Campo_56d_Opt2, string lsB4_Campo_56d_Desc1, string lsB4_Campo_56d_Desc2, string lsB4_Campo_56d_Desc3, string lsB4_Campo_56d_Desc4, string lsB4_Campo_57d_Opt1, string lsB4_Campo_57d_Opt2, string lsB4_Campo_57d_Desc1, string lsB4_Campo_57d_Desc2, string lsB4_Campo_57d_Desc3, string lsB4_Campo_57d_Desc4, string lsB4_Campo_59_Filler, string lsB4_Campo_59_Cta_Benef, string lsB4_Campo_59_Benef1, string lsB4_Campo_59_Benef2, string lsB4_Campo_59_Benef3, string lsB4_Campo_59_Benef4, string lsB4_Campo_70_Ref1, string lsB4_Campo_70_Ref2, string lsB4_Campo_70_Ref3, string lsB4_Campo_70_Ref4)
        {
            var lsNumero_MovimientoParameter = lsNumero_Movimiento != null ?
                new ObjectParameter("LsNumero_Movimiento", lsNumero_Movimiento) :
                new ObjectParameter("LsNumero_Movimiento", typeof(string));
    
            var lsB1_IndentificadorParameter = lsB1_Indentificador != null ?
                new ObjectParameter("LsB1_Indentificador", lsB1_Indentificador) :
                new ObjectParameter("LsB1_Indentificador", typeof(string));
    
            var lsB1_Identificador_AplicParameter = lsB1_Identificador_Aplic != null ?
                new ObjectParameter("LsB1_Identificador_Aplic", lsB1_Identificador_Aplic) :
                new ObjectParameter("LsB1_Identificador_Aplic", typeof(string));
    
            var lsB1_Identificador_ServParameter = lsB1_Identificador_Serv != null ?
                new ObjectParameter("LsB1_Identificador_Serv", lsB1_Identificador_Serv) :
                new ObjectParameter("LsB1_Identificador_Serv", typeof(string));
    
            var lsB1_Direccion_SwiftParameter = lsB1_Direccion_Swift != null ?
                new ObjectParameter("LsB1_Direccion_Swift", lsB1_Direccion_Swift) :
                new ObjectParameter("LsB1_Direccion_Swift", typeof(string));
    
            var lsB1_Ind_AplicacionParameter = lsB1_Ind_Aplicacion != null ?
                new ObjectParameter("LsB1_Ind_Aplicacion", lsB1_Ind_Aplicacion) :
                new ObjectParameter("LsB1_Ind_Aplicacion", typeof(string));
    
            var lsB1_Branch_CodeParameter = lsB1_Branch_Code != null ?
                new ObjectParameter("LsB1_Branch_Code", lsB1_Branch_Code) :
                new ObjectParameter("LsB1_Branch_Code", typeof(string));
    
            var lsB2_IdentificadorParameter = lsB2_Identificador != null ?
                new ObjectParameter("LsB2_Identificador", lsB2_Identificador) :
                new ObjectParameter("LsB2_Identificador", typeof(string));
    
            var lsB2_Identificador_ioParameter = lsB2_Identificador_io != null ?
                new ObjectParameter("LsB2_Identificador_io", lsB2_Identificador_io) :
                new ObjectParameter("LsB2_Identificador_io", typeof(string));
    
            var lsB2_Tipo_MensajeParameter = lsB2_Tipo_Mensaje != null ?
                new ObjectParameter("LsB2_Tipo_Mensaje", lsB2_Tipo_Mensaje) :
                new ObjectParameter("LsB2_Tipo_Mensaje", typeof(string));
    
            var lsB2_Direccion_SwiftParameter = lsB2_Direccion_Swift != null ?
                new ObjectParameter("LsB2_Direccion_Swift", lsB2_Direccion_Swift) :
                new ObjectParameter("LsB2_Direccion_Swift", typeof(string));
    
            var lsB2_Ind_AplicacionParameter = lsB2_Ind_Aplicacion != null ?
                new ObjectParameter("LsB2_Ind_Aplicacion", lsB2_Ind_Aplicacion) :
                new ObjectParameter("LsB2_Ind_Aplicacion", typeof(string));
    
            var lsB2_Branch_CodeParameter = lsB2_Branch_Code != null ?
                new ObjectParameter("LsB2_Branch_Code", lsB2_Branch_Code) :
                new ObjectParameter("LsB2_Branch_Code", typeof(string));
    
            var lsB2_PrioridadParameter = lsB2_Prioridad != null ?
                new ObjectParameter("LsB2_Prioridad", lsB2_Prioridad) :
                new ObjectParameter("LsB2_Prioridad", typeof(string));
    
            var lsB3_IdentificadorParameter = lsB3_Identificador != null ?
                new ObjectParameter("LsB3_Identificador", lsB3_Identificador) :
                new ObjectParameter("LsB3_Identificador", typeof(string));
    
            var lsB3_Tipo_MensajeParameter = lsB3_Tipo_Mensaje != null ?
                new ObjectParameter("LsB3_Tipo_Mensaje", lsB3_Tipo_Mensaje) :
                new ObjectParameter("LsB3_Tipo_Mensaje", typeof(string));
    
            var lsB3_TextoParameter = lsB3_Texto != null ?
                new ObjectParameter("LsB3_Texto", lsB3_Texto) :
                new ObjectParameter("LsB3_Texto", typeof(string));
    
            var lsB4_IdentificadorParameter = lsB4_Identificador != null ?
                new ObjectParameter("LsB4_Identificador", lsB4_Identificador) :
                new ObjectParameter("LsB4_Identificador", typeof(string));
    
            var lsB4_Campo_20Parameter = lsB4_Campo_20 != null ?
                new ObjectParameter("LsB4_Campo_20", lsB4_Campo_20) :
                new ObjectParameter("LsB4_Campo_20", typeof(string));
    
            var lsB4_Campo_23bParameter = lsB4_Campo_23b != null ?
                new ObjectParameter("LsB4_Campo_23b", lsB4_Campo_23b) :
                new ObjectParameter("LsB4_Campo_23b", typeof(string));
    
            var lsB4_Campo_32a_FechaParameter = lsB4_Campo_32a_Fecha != null ?
                new ObjectParameter("LsB4_Campo_32a_Fecha", lsB4_Campo_32a_Fecha) :
                new ObjectParameter("LsB4_Campo_32a_Fecha", typeof(string));
    
            var lsB4_Campo_32a_MonedaParameter = lsB4_Campo_32a_Moneda != null ?
                new ObjectParameter("LsB4_Campo_32a_Moneda", lsB4_Campo_32a_Moneda) :
                new ObjectParameter("LsB4_Campo_32a_Moneda", typeof(string));
    
            var lsB4_Campo_32a_MontoParameter = lsB4_Campo_32a_Monto != null ?
                new ObjectParameter("LsB4_Campo_32a_Monto", lsB4_Campo_32a_Monto) :
                new ObjectParameter("LsB4_Campo_32a_Monto", typeof(string));
    
            var lsB4_Campo_50k_CuentaParameter = lsB4_Campo_50k_Cuenta != null ?
                new ObjectParameter("LsB4_Campo_50k_Cuenta", lsB4_Campo_50k_Cuenta) :
                new ObjectParameter("LsB4_Campo_50k_Cuenta", typeof(string));
    
            var lsB4_Campo_50k_Direc1Parameter = lsB4_Campo_50k_Direc1 != null ?
                new ObjectParameter("LsB4_Campo_50k_Direc1", lsB4_Campo_50k_Direc1) :
                new ObjectParameter("LsB4_Campo_50k_Direc1", typeof(string));
    
            var lsB4_Campo_50k_Direc2Parameter = lsB4_Campo_50k_Direc2 != null ?
                new ObjectParameter("LsB4_Campo_50k_Direc2", lsB4_Campo_50k_Direc2) :
                new ObjectParameter("LsB4_Campo_50k_Direc2", typeof(string));
    
            var lsB4_Campo_50k_Direc3Parameter = lsB4_Campo_50k_Direc3 != null ?
                new ObjectParameter("LsB4_Campo_50k_Direc3", lsB4_Campo_50k_Direc3) :
                new ObjectParameter("LsB4_Campo_50k_Direc3", typeof(string));
    
            var lsB4_Campo_50k_Direc4Parameter = lsB4_Campo_50k_Direc4 != null ?
                new ObjectParameter("LsB4_Campo_50k_Direc4", lsB4_Campo_50k_Direc4) :
                new ObjectParameter("LsB4_Campo_50k_Direc4", typeof(string));
    
            var lsB4_Campo_53d_Opt1Parameter = lsB4_Campo_53d_Opt1 != null ?
                new ObjectParameter("LsB4_Campo_53d_Opt1", lsB4_Campo_53d_Opt1) :
                new ObjectParameter("LsB4_Campo_53d_Opt1", typeof(string));
    
            var lsB4_Campo_53d_Opt2Parameter = lsB4_Campo_53d_Opt2 != null ?
                new ObjectParameter("LsB4_Campo_53d_Opt2", lsB4_Campo_53d_Opt2) :
                new ObjectParameter("LsB4_Campo_53d_Opt2", typeof(string));
    
            var lsB4_Campo_53d_Desc1Parameter = lsB4_Campo_53d_Desc1 != null ?
                new ObjectParameter("LsB4_Campo_53d_Desc1", lsB4_Campo_53d_Desc1) :
                new ObjectParameter("LsB4_Campo_53d_Desc1", typeof(string));
    
            var lsB4_Campo_53d_Desc2Parameter = lsB4_Campo_53d_Desc2 != null ?
                new ObjectParameter("LsB4_Campo_53d_Desc2", lsB4_Campo_53d_Desc2) :
                new ObjectParameter("LsB4_Campo_53d_Desc2", typeof(string));
    
            var lsB4_Campo_53d_Desc3Parameter = lsB4_Campo_53d_Desc3 != null ?
                new ObjectParameter("LsB4_Campo_53d_Desc3", lsB4_Campo_53d_Desc3) :
                new ObjectParameter("LsB4_Campo_53d_Desc3", typeof(string));
    
            var lsB4_Campo_53d_Desc4Parameter = lsB4_Campo_53d_Desc4 != null ?
                new ObjectParameter("LsB4_Campo_53d_Desc4", lsB4_Campo_53d_Desc4) :
                new ObjectParameter("LsB4_Campo_53d_Desc4", typeof(string));
    
            var lsB4_Campo_56d_Opt1Parameter = lsB4_Campo_56d_Opt1 != null ?
                new ObjectParameter("LsB4_Campo_56d_Opt1", lsB4_Campo_56d_Opt1) :
                new ObjectParameter("LsB4_Campo_56d_Opt1", typeof(string));
    
            var lsB4_Campo_56d_Opt2Parameter = lsB4_Campo_56d_Opt2 != null ?
                new ObjectParameter("LsB4_Campo_56d_Opt2", lsB4_Campo_56d_Opt2) :
                new ObjectParameter("LsB4_Campo_56d_Opt2", typeof(string));
    
            var lsB4_Campo_56d_Desc1Parameter = lsB4_Campo_56d_Desc1 != null ?
                new ObjectParameter("LsB4_Campo_56d_Desc1", lsB4_Campo_56d_Desc1) :
                new ObjectParameter("LsB4_Campo_56d_Desc1", typeof(string));
    
            var lsB4_Campo_56d_Desc2Parameter = lsB4_Campo_56d_Desc2 != null ?
                new ObjectParameter("LsB4_Campo_56d_Desc2", lsB4_Campo_56d_Desc2) :
                new ObjectParameter("LsB4_Campo_56d_Desc2", typeof(string));
    
            var lsB4_Campo_56d_Desc3Parameter = lsB4_Campo_56d_Desc3 != null ?
                new ObjectParameter("LsB4_Campo_56d_Desc3", lsB4_Campo_56d_Desc3) :
                new ObjectParameter("LsB4_Campo_56d_Desc3", typeof(string));
    
            var lsB4_Campo_56d_Desc4Parameter = lsB4_Campo_56d_Desc4 != null ?
                new ObjectParameter("LsB4_Campo_56d_Desc4", lsB4_Campo_56d_Desc4) :
                new ObjectParameter("LsB4_Campo_56d_Desc4", typeof(string));
    
            var lsB4_Campo_57d_Opt1Parameter = lsB4_Campo_57d_Opt1 != null ?
                new ObjectParameter("LsB4_Campo_57d_Opt1", lsB4_Campo_57d_Opt1) :
                new ObjectParameter("LsB4_Campo_57d_Opt1", typeof(string));
    
            var lsB4_Campo_57d_Opt2Parameter = lsB4_Campo_57d_Opt2 != null ?
                new ObjectParameter("LsB4_Campo_57d_Opt2", lsB4_Campo_57d_Opt2) :
                new ObjectParameter("LsB4_Campo_57d_Opt2", typeof(string));
    
            var lsB4_Campo_57d_Desc1Parameter = lsB4_Campo_57d_Desc1 != null ?
                new ObjectParameter("LsB4_Campo_57d_Desc1", lsB4_Campo_57d_Desc1) :
                new ObjectParameter("LsB4_Campo_57d_Desc1", typeof(string));
    
            var lsB4_Campo_57d_Desc2Parameter = lsB4_Campo_57d_Desc2 != null ?
                new ObjectParameter("LsB4_Campo_57d_Desc2", lsB4_Campo_57d_Desc2) :
                new ObjectParameter("LsB4_Campo_57d_Desc2", typeof(string));
    
            var lsB4_Campo_57d_Desc3Parameter = lsB4_Campo_57d_Desc3 != null ?
                new ObjectParameter("LsB4_Campo_57d_Desc3", lsB4_Campo_57d_Desc3) :
                new ObjectParameter("LsB4_Campo_57d_Desc3", typeof(string));
    
            var lsB4_Campo_57d_Desc4Parameter = lsB4_Campo_57d_Desc4 != null ?
                new ObjectParameter("LsB4_Campo_57d_Desc4", lsB4_Campo_57d_Desc4) :
                new ObjectParameter("LsB4_Campo_57d_Desc4", typeof(string));
    
            var lsB4_Campo_59_FillerParameter = lsB4_Campo_59_Filler != null ?
                new ObjectParameter("LsB4_Campo_59_Filler", lsB4_Campo_59_Filler) :
                new ObjectParameter("LsB4_Campo_59_Filler", typeof(string));
    
            var lsB4_Campo_59_Cta_BenefParameter = lsB4_Campo_59_Cta_Benef != null ?
                new ObjectParameter("LsB4_Campo_59_Cta_Benef", lsB4_Campo_59_Cta_Benef) :
                new ObjectParameter("LsB4_Campo_59_Cta_Benef", typeof(string));
    
            var lsB4_Campo_59_Benef1Parameter = lsB4_Campo_59_Benef1 != null ?
                new ObjectParameter("LsB4_Campo_59_Benef1", lsB4_Campo_59_Benef1) :
                new ObjectParameter("LsB4_Campo_59_Benef1", typeof(string));
    
            var lsB4_Campo_59_Benef2Parameter = lsB4_Campo_59_Benef2 != null ?
                new ObjectParameter("LsB4_Campo_59_Benef2", lsB4_Campo_59_Benef2) :
                new ObjectParameter("LsB4_Campo_59_Benef2", typeof(string));
    
            var lsB4_Campo_59_Benef3Parameter = lsB4_Campo_59_Benef3 != null ?
                new ObjectParameter("LsB4_Campo_59_Benef3", lsB4_Campo_59_Benef3) :
                new ObjectParameter("LsB4_Campo_59_Benef3", typeof(string));
    
            var lsB4_Campo_59_Benef4Parameter = lsB4_Campo_59_Benef4 != null ?
                new ObjectParameter("LsB4_Campo_59_Benef4", lsB4_Campo_59_Benef4) :
                new ObjectParameter("LsB4_Campo_59_Benef4", typeof(string));
    
            var lsB4_Campo_70_Ref1Parameter = lsB4_Campo_70_Ref1 != null ?
                new ObjectParameter("LsB4_Campo_70_Ref1", lsB4_Campo_70_Ref1) :
                new ObjectParameter("LsB4_Campo_70_Ref1", typeof(string));
    
            var lsB4_Campo_70_Ref2Parameter = lsB4_Campo_70_Ref2 != null ?
                new ObjectParameter("LsB4_Campo_70_Ref2", lsB4_Campo_70_Ref2) :
                new ObjectParameter("LsB4_Campo_70_Ref2", typeof(string));
    
            var lsB4_Campo_70_Ref3Parameter = lsB4_Campo_70_Ref3 != null ?
                new ObjectParameter("LsB4_Campo_70_Ref3", lsB4_Campo_70_Ref3) :
                new ObjectParameter("LsB4_Campo_70_Ref3", typeof(string));
    
            var lsB4_Campo_70_Ref4Parameter = lsB4_Campo_70_Ref4 != null ?
                new ObjectParameter("LsB4_Campo_70_Ref4", lsB4_Campo_70_Ref4) :
                new ObjectParameter("LsB4_Campo_70_Ref4", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_piu_gen_retiro_MT103_Result>("sp_piu_gen_retiro_MT103", lsNumero_MovimientoParameter, lsB1_IndentificadorParameter, lsB1_Identificador_AplicParameter, lsB1_Identificador_ServParameter, lsB1_Direccion_SwiftParameter, lsB1_Ind_AplicacionParameter, lsB1_Branch_CodeParameter, lsB2_IdentificadorParameter, lsB2_Identificador_ioParameter, lsB2_Tipo_MensajeParameter, lsB2_Direccion_SwiftParameter, lsB2_Ind_AplicacionParameter, lsB2_Branch_CodeParameter, lsB2_PrioridadParameter, lsB3_IdentificadorParameter, lsB3_Tipo_MensajeParameter, lsB3_TextoParameter, lsB4_IdentificadorParameter, lsB4_Campo_20Parameter, lsB4_Campo_23bParameter, lsB4_Campo_32a_FechaParameter, lsB4_Campo_32a_MonedaParameter, lsB4_Campo_32a_MontoParameter, lsB4_Campo_50k_CuentaParameter, lsB4_Campo_50k_Direc1Parameter, lsB4_Campo_50k_Direc2Parameter, lsB4_Campo_50k_Direc3Parameter, lsB4_Campo_50k_Direc4Parameter, lsB4_Campo_53d_Opt1Parameter, lsB4_Campo_53d_Opt2Parameter, lsB4_Campo_53d_Desc1Parameter, lsB4_Campo_53d_Desc2Parameter, lsB4_Campo_53d_Desc3Parameter, lsB4_Campo_53d_Desc4Parameter, lsB4_Campo_56d_Opt1Parameter, lsB4_Campo_56d_Opt2Parameter, lsB4_Campo_56d_Desc1Parameter, lsB4_Campo_56d_Desc2Parameter, lsB4_Campo_56d_Desc3Parameter, lsB4_Campo_56d_Desc4Parameter, lsB4_Campo_57d_Opt1Parameter, lsB4_Campo_57d_Opt2Parameter, lsB4_Campo_57d_Desc1Parameter, lsB4_Campo_57d_Desc2Parameter, lsB4_Campo_57d_Desc3Parameter, lsB4_Campo_57d_Desc4Parameter, lsB4_Campo_59_FillerParameter, lsB4_Campo_59_Cta_BenefParameter, lsB4_Campo_59_Benef1Parameter, lsB4_Campo_59_Benef2Parameter, lsB4_Campo_59_Benef3Parameter, lsB4_Campo_59_Benef4Parameter, lsB4_Campo_70_Ref1Parameter, lsB4_Campo_70_Ref2Parameter, lsB4_Campo_70_Ref3Parameter, lsB4_Campo_70_Ref4Parameter);
        }
    
        public virtual ObjectResult<sp_piu_gen_retiro_XML103_Result> sp_piu_gen_retiro_XML103(string lsNumero_Movimiento, string lsB1_Direccion_Swift, string lsB1_Ind_Aplicacion, string lsB1_Branch_Code, string lsB2_Tipo_Mensaje, string lsB2_Direccion_Swift, string lsB2_Ind_Aplicacion, string lsB2_Branch_Code, string lsB2_Prioridad, string lsB3_Tipo_Mensaje, string lsB3_Texto, string lsB4_Campo_20, string lsB4_Campo_23b, string lsB4_Campo_32a_Fecha, string lsB4_Campo_32a_Moneda, string lsB4_Campo_32a_Monto, string lsB4_Campo_50k_Cuenta, string lsB4_Campo_50k_Nombre, string lsB4_Campo_50_Nom_Calle, string lsB4_Campo_50_Num_Edi, string lsB4_Campo_50_Cod_Pos, string lsB4_Campo_50_Ubi_Cd, string lsB4_Campo_50_region, string lsB4_Campo_50_cod_pais, string lsB4_Campo_53d_Opt1, string lsB4_Campo_53d_Opt2, string lsB4_Campo_53d_Nombre, string lsB4_Campo_56d_Opt1, string lsB4_Campo_56d_Opt2, string lsB4_Campo_56d_Desc1, string lsB4_Campo_56d_NomCalle, string lsB4_Campo_56d_Num_Edi, string lsB4_Campo_56d_Cod_Pos, string lsB4_Campo_56d_Ubi_Cd, string lsB4_Campo_56d_Region, string lsB4_Campo_56d_cod_pais, string lsB4_Campo_56d_Adrline, string lsB4_Campo_57d_Opt1, string lsB4_Campo_57d_Opt2, string lsB4_Campo_57d_Desc1, string lsB4_Campo_57d_NomCalle, string lsB4_Campo_57d_Num_Edi, string lsB4_Campo_57d_Cod_Pos, string lsB4_Campo_57d_Ubi_Cd, string lsB4_Campo_57d_Region, string lsB4_Campo_57d_cod_pais, string lsB4_Campo_57d_Adrline, string lsB4_Campo_59_Filler, string lsB4_Campo_59_Cta_Benef, string lsB4_Campo_59_Nombre, string lsB4_Campo_59_Nom_Calle, string lsB4_Campo_59_Num_Edi, string lsB4_Campo_59_Cod_Pos, string lsB4_Campo_59_Ubi_Cd, string lsB4_Campo_59_region, string lsB4_Campo_59_cod_pais, string lsB4_Campo_57_concepto)
        {
            var lsNumero_MovimientoParameter = lsNumero_Movimiento != null ?
                new ObjectParameter("LsNumero_Movimiento", lsNumero_Movimiento) :
                new ObjectParameter("LsNumero_Movimiento", typeof(string));
    
            var lsB1_Direccion_SwiftParameter = lsB1_Direccion_Swift != null ?
                new ObjectParameter("LsB1_Direccion_Swift", lsB1_Direccion_Swift) :
                new ObjectParameter("LsB1_Direccion_Swift", typeof(string));
    
            var lsB1_Ind_AplicacionParameter = lsB1_Ind_Aplicacion != null ?
                new ObjectParameter("LsB1_Ind_Aplicacion", lsB1_Ind_Aplicacion) :
                new ObjectParameter("LsB1_Ind_Aplicacion", typeof(string));
    
            var lsB1_Branch_CodeParameter = lsB1_Branch_Code != null ?
                new ObjectParameter("LsB1_Branch_Code", lsB1_Branch_Code) :
                new ObjectParameter("LsB1_Branch_Code", typeof(string));
    
            var lsB2_Tipo_MensajeParameter = lsB2_Tipo_Mensaje != null ?
                new ObjectParameter("LsB2_Tipo_Mensaje", lsB2_Tipo_Mensaje) :
                new ObjectParameter("LsB2_Tipo_Mensaje", typeof(string));
    
            var lsB2_Direccion_SwiftParameter = lsB2_Direccion_Swift != null ?
                new ObjectParameter("LsB2_Direccion_Swift", lsB2_Direccion_Swift) :
                new ObjectParameter("LsB2_Direccion_Swift", typeof(string));
    
            var lsB2_Ind_AplicacionParameter = lsB2_Ind_Aplicacion != null ?
                new ObjectParameter("LsB2_Ind_Aplicacion", lsB2_Ind_Aplicacion) :
                new ObjectParameter("LsB2_Ind_Aplicacion", typeof(string));
    
            var lsB2_Branch_CodeParameter = lsB2_Branch_Code != null ?
                new ObjectParameter("LsB2_Branch_Code", lsB2_Branch_Code) :
                new ObjectParameter("LsB2_Branch_Code", typeof(string));
    
            var lsB2_PrioridadParameter = lsB2_Prioridad != null ?
                new ObjectParameter("LsB2_Prioridad", lsB2_Prioridad) :
                new ObjectParameter("LsB2_Prioridad", typeof(string));
    
            var lsB3_Tipo_MensajeParameter = lsB3_Tipo_Mensaje != null ?
                new ObjectParameter("LsB3_Tipo_Mensaje", lsB3_Tipo_Mensaje) :
                new ObjectParameter("LsB3_Tipo_Mensaje", typeof(string));
    
            var lsB3_TextoParameter = lsB3_Texto != null ?
                new ObjectParameter("LsB3_Texto", lsB3_Texto) :
                new ObjectParameter("LsB3_Texto", typeof(string));
    
            var lsB4_Campo_20Parameter = lsB4_Campo_20 != null ?
                new ObjectParameter("LsB4_Campo_20", lsB4_Campo_20) :
                new ObjectParameter("LsB4_Campo_20", typeof(string));
    
            var lsB4_Campo_23bParameter = lsB4_Campo_23b != null ?
                new ObjectParameter("LsB4_Campo_23b", lsB4_Campo_23b) :
                new ObjectParameter("LsB4_Campo_23b", typeof(string));
    
            var lsB4_Campo_32a_FechaParameter = lsB4_Campo_32a_Fecha != null ?
                new ObjectParameter("LsB4_Campo_32a_Fecha", lsB4_Campo_32a_Fecha) :
                new ObjectParameter("LsB4_Campo_32a_Fecha", typeof(string));
    
            var lsB4_Campo_32a_MonedaParameter = lsB4_Campo_32a_Moneda != null ?
                new ObjectParameter("LsB4_Campo_32a_Moneda", lsB4_Campo_32a_Moneda) :
                new ObjectParameter("LsB4_Campo_32a_Moneda", typeof(string));
    
            var lsB4_Campo_32a_MontoParameter = lsB4_Campo_32a_Monto != null ?
                new ObjectParameter("LsB4_Campo_32a_Monto", lsB4_Campo_32a_Monto) :
                new ObjectParameter("LsB4_Campo_32a_Monto", typeof(string));
    
            var lsB4_Campo_50k_CuentaParameter = lsB4_Campo_50k_Cuenta != null ?
                new ObjectParameter("LsB4_Campo_50k_Cuenta", lsB4_Campo_50k_Cuenta) :
                new ObjectParameter("LsB4_Campo_50k_Cuenta", typeof(string));
    
            var lsB4_Campo_50k_NombreParameter = lsB4_Campo_50k_Nombre != null ?
                new ObjectParameter("LsB4_Campo_50k_Nombre", lsB4_Campo_50k_Nombre) :
                new ObjectParameter("LsB4_Campo_50k_Nombre", typeof(string));
    
            var lsB4_Campo_50_Nom_CalleParameter = lsB4_Campo_50_Nom_Calle != null ?
                new ObjectParameter("LsB4_Campo_50_Nom_Calle", lsB4_Campo_50_Nom_Calle) :
                new ObjectParameter("LsB4_Campo_50_Nom_Calle", typeof(string));
    
            var lsB4_Campo_50_Num_EdiParameter = lsB4_Campo_50_Num_Edi != null ?
                new ObjectParameter("LsB4_Campo_50_Num_Edi", lsB4_Campo_50_Num_Edi) :
                new ObjectParameter("LsB4_Campo_50_Num_Edi", typeof(string));
    
            var lsB4_Campo_50_Cod_PosParameter = lsB4_Campo_50_Cod_Pos != null ?
                new ObjectParameter("LsB4_Campo_50_Cod_Pos", lsB4_Campo_50_Cod_Pos) :
                new ObjectParameter("LsB4_Campo_50_Cod_Pos", typeof(string));
    
            var lsB4_Campo_50_Ubi_CdParameter = lsB4_Campo_50_Ubi_Cd != null ?
                new ObjectParameter("LsB4_Campo_50_Ubi_Cd", lsB4_Campo_50_Ubi_Cd) :
                new ObjectParameter("LsB4_Campo_50_Ubi_Cd", typeof(string));
    
            var lsB4_Campo_50_regionParameter = lsB4_Campo_50_region != null ?
                new ObjectParameter("LsB4_Campo_50_region", lsB4_Campo_50_region) :
                new ObjectParameter("LsB4_Campo_50_region", typeof(string));
    
            var lsB4_Campo_50_cod_paisParameter = lsB4_Campo_50_cod_pais != null ?
                new ObjectParameter("LsB4_Campo_50_cod_pais", lsB4_Campo_50_cod_pais) :
                new ObjectParameter("LsB4_Campo_50_cod_pais", typeof(string));
    
            var lsB4_Campo_53d_Opt1Parameter = lsB4_Campo_53d_Opt1 != null ?
                new ObjectParameter("LsB4_Campo_53d_Opt1", lsB4_Campo_53d_Opt1) :
                new ObjectParameter("LsB4_Campo_53d_Opt1", typeof(string));
    
            var lsB4_Campo_53d_Opt2Parameter = lsB4_Campo_53d_Opt2 != null ?
                new ObjectParameter("LsB4_Campo_53d_Opt2", lsB4_Campo_53d_Opt2) :
                new ObjectParameter("LsB4_Campo_53d_Opt2", typeof(string));
    
            var lsB4_Campo_53d_NombreParameter = lsB4_Campo_53d_Nombre != null ?
                new ObjectParameter("LsB4_Campo_53d_Nombre", lsB4_Campo_53d_Nombre) :
                new ObjectParameter("LsB4_Campo_53d_Nombre", typeof(string));
    
            var lsB4_Campo_56d_Opt1Parameter = lsB4_Campo_56d_Opt1 != null ?
                new ObjectParameter("LsB4_Campo_56d_Opt1", lsB4_Campo_56d_Opt1) :
                new ObjectParameter("LsB4_Campo_56d_Opt1", typeof(string));
    
            var lsB4_Campo_56d_Opt2Parameter = lsB4_Campo_56d_Opt2 != null ?
                new ObjectParameter("LsB4_Campo_56d_Opt2", lsB4_Campo_56d_Opt2) :
                new ObjectParameter("LsB4_Campo_56d_Opt2", typeof(string));
    
            var lsB4_Campo_56d_Desc1Parameter = lsB4_Campo_56d_Desc1 != null ?
                new ObjectParameter("LsB4_Campo_56d_Desc1", lsB4_Campo_56d_Desc1) :
                new ObjectParameter("LsB4_Campo_56d_Desc1", typeof(string));
    
            var lsB4_Campo_56d_NomCalleParameter = lsB4_Campo_56d_NomCalle != null ?
                new ObjectParameter("LsB4_Campo_56d_NomCalle", lsB4_Campo_56d_NomCalle) :
                new ObjectParameter("LsB4_Campo_56d_NomCalle", typeof(string));
    
            var lsB4_Campo_56d_Num_EdiParameter = lsB4_Campo_56d_Num_Edi != null ?
                new ObjectParameter("LsB4_Campo_56d_Num_Edi", lsB4_Campo_56d_Num_Edi) :
                new ObjectParameter("LsB4_Campo_56d_Num_Edi", typeof(string));
    
            var lsB4_Campo_56d_Cod_PosParameter = lsB4_Campo_56d_Cod_Pos != null ?
                new ObjectParameter("LsB4_Campo_56d_Cod_Pos", lsB4_Campo_56d_Cod_Pos) :
                new ObjectParameter("LsB4_Campo_56d_Cod_Pos", typeof(string));
    
            var lsB4_Campo_56d_Ubi_CdParameter = lsB4_Campo_56d_Ubi_Cd != null ?
                new ObjectParameter("LsB4_Campo_56d_Ubi_Cd", lsB4_Campo_56d_Ubi_Cd) :
                new ObjectParameter("LsB4_Campo_56d_Ubi_Cd", typeof(string));
    
            var lsB4_Campo_56d_RegionParameter = lsB4_Campo_56d_Region != null ?
                new ObjectParameter("LsB4_Campo_56d_Region", lsB4_Campo_56d_Region) :
                new ObjectParameter("LsB4_Campo_56d_Region", typeof(string));
    
            var lsB4_Campo_56d_cod_paisParameter = lsB4_Campo_56d_cod_pais != null ?
                new ObjectParameter("LsB4_Campo_56d_cod_pais", lsB4_Campo_56d_cod_pais) :
                new ObjectParameter("LsB4_Campo_56d_cod_pais", typeof(string));
    
            var lsB4_Campo_56d_AdrlineParameter = lsB4_Campo_56d_Adrline != null ?
                new ObjectParameter("LsB4_Campo_56d_Adrline", lsB4_Campo_56d_Adrline) :
                new ObjectParameter("LsB4_Campo_56d_Adrline", typeof(string));
    
            var lsB4_Campo_57d_Opt1Parameter = lsB4_Campo_57d_Opt1 != null ?
                new ObjectParameter("LsB4_Campo_57d_Opt1", lsB4_Campo_57d_Opt1) :
                new ObjectParameter("LsB4_Campo_57d_Opt1", typeof(string));
    
            var lsB4_Campo_57d_Opt2Parameter = lsB4_Campo_57d_Opt2 != null ?
                new ObjectParameter("LsB4_Campo_57d_Opt2", lsB4_Campo_57d_Opt2) :
                new ObjectParameter("LsB4_Campo_57d_Opt2", typeof(string));
    
            var lsB4_Campo_57d_Desc1Parameter = lsB4_Campo_57d_Desc1 != null ?
                new ObjectParameter("LsB4_Campo_57d_Desc1", lsB4_Campo_57d_Desc1) :
                new ObjectParameter("LsB4_Campo_57d_Desc1", typeof(string));
    
            var lsB4_Campo_57d_NomCalleParameter = lsB4_Campo_57d_NomCalle != null ?
                new ObjectParameter("LsB4_Campo_57d_NomCalle", lsB4_Campo_57d_NomCalle) :
                new ObjectParameter("LsB4_Campo_57d_NomCalle", typeof(string));
    
            var lsB4_Campo_57d_Num_EdiParameter = lsB4_Campo_57d_Num_Edi != null ?
                new ObjectParameter("LsB4_Campo_57d_Num_Edi", lsB4_Campo_57d_Num_Edi) :
                new ObjectParameter("LsB4_Campo_57d_Num_Edi", typeof(string));
    
            var lsB4_Campo_57d_Cod_PosParameter = lsB4_Campo_57d_Cod_Pos != null ?
                new ObjectParameter("LsB4_Campo_57d_Cod_Pos", lsB4_Campo_57d_Cod_Pos) :
                new ObjectParameter("LsB4_Campo_57d_Cod_Pos", typeof(string));
    
            var lsB4_Campo_57d_Ubi_CdParameter = lsB4_Campo_57d_Ubi_Cd != null ?
                new ObjectParameter("LsB4_Campo_57d_Ubi_Cd", lsB4_Campo_57d_Ubi_Cd) :
                new ObjectParameter("LsB4_Campo_57d_Ubi_Cd", typeof(string));
    
            var lsB4_Campo_57d_RegionParameter = lsB4_Campo_57d_Region != null ?
                new ObjectParameter("LsB4_Campo_57d_Region", lsB4_Campo_57d_Region) :
                new ObjectParameter("LsB4_Campo_57d_Region", typeof(string));
    
            var lsB4_Campo_57d_cod_paisParameter = lsB4_Campo_57d_cod_pais != null ?
                new ObjectParameter("LsB4_Campo_57d_cod_pais", lsB4_Campo_57d_cod_pais) :
                new ObjectParameter("LsB4_Campo_57d_cod_pais", typeof(string));
    
            var lsB4_Campo_57d_AdrlineParameter = lsB4_Campo_57d_Adrline != null ?
                new ObjectParameter("LsB4_Campo_57d_Adrline", lsB4_Campo_57d_Adrline) :
                new ObjectParameter("LsB4_Campo_57d_Adrline", typeof(string));
    
            var lsB4_Campo_59_FillerParameter = lsB4_Campo_59_Filler != null ?
                new ObjectParameter("LsB4_Campo_59_Filler", lsB4_Campo_59_Filler) :
                new ObjectParameter("LsB4_Campo_59_Filler", typeof(string));
    
            var lsB4_Campo_59_Cta_BenefParameter = lsB4_Campo_59_Cta_Benef != null ?
                new ObjectParameter("LsB4_Campo_59_Cta_Benef", lsB4_Campo_59_Cta_Benef) :
                new ObjectParameter("LsB4_Campo_59_Cta_Benef", typeof(string));
    
            var lsB4_Campo_59_NombreParameter = lsB4_Campo_59_Nombre != null ?
                new ObjectParameter("LsB4_Campo_59_Nombre", lsB4_Campo_59_Nombre) :
                new ObjectParameter("LsB4_Campo_59_Nombre", typeof(string));
    
            var lsB4_Campo_59_Nom_CalleParameter = lsB4_Campo_59_Nom_Calle != null ?
                new ObjectParameter("LsB4_Campo_59_Nom_Calle", lsB4_Campo_59_Nom_Calle) :
                new ObjectParameter("LsB4_Campo_59_Nom_Calle", typeof(string));
    
            var lsB4_Campo_59_Num_EdiParameter = lsB4_Campo_59_Num_Edi != null ?
                new ObjectParameter("LsB4_Campo_59_Num_Edi", lsB4_Campo_59_Num_Edi) :
                new ObjectParameter("LsB4_Campo_59_Num_Edi", typeof(string));
    
            var lsB4_Campo_59_Cod_PosParameter = lsB4_Campo_59_Cod_Pos != null ?
                new ObjectParameter("LsB4_Campo_59_Cod_Pos", lsB4_Campo_59_Cod_Pos) :
                new ObjectParameter("LsB4_Campo_59_Cod_Pos", typeof(string));
    
            var lsB4_Campo_59_Ubi_CdParameter = lsB4_Campo_59_Ubi_Cd != null ?
                new ObjectParameter("LsB4_Campo_59_Ubi_Cd", lsB4_Campo_59_Ubi_Cd) :
                new ObjectParameter("LsB4_Campo_59_Ubi_Cd", typeof(string));
    
            var lsB4_Campo_59_regionParameter = lsB4_Campo_59_region != null ?
                new ObjectParameter("LsB4_Campo_59_region", lsB4_Campo_59_region) :
                new ObjectParameter("LsB4_Campo_59_region", typeof(string));
    
            var lsB4_Campo_59_cod_paisParameter = lsB4_Campo_59_cod_pais != null ?
                new ObjectParameter("LsB4_Campo_59_cod_pais", lsB4_Campo_59_cod_pais) :
                new ObjectParameter("LsB4_Campo_59_cod_pais", typeof(string));
    
            var lsB4_Campo_57_conceptoParameter = lsB4_Campo_57_concepto != null ?
                new ObjectParameter("LsB4_Campo_57_concepto", lsB4_Campo_57_concepto) :
                new ObjectParameter("LsB4_Campo_57_concepto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_piu_gen_retiro_XML103_Result>("sp_piu_gen_retiro_XML103", lsNumero_MovimientoParameter, lsB1_Direccion_SwiftParameter, lsB1_Ind_AplicacionParameter, lsB1_Branch_CodeParameter, lsB2_Tipo_MensajeParameter, lsB2_Direccion_SwiftParameter, lsB2_Ind_AplicacionParameter, lsB2_Branch_CodeParameter, lsB2_PrioridadParameter, lsB3_Tipo_MensajeParameter, lsB3_TextoParameter, lsB4_Campo_20Parameter, lsB4_Campo_23bParameter, lsB4_Campo_32a_FechaParameter, lsB4_Campo_32a_MonedaParameter, lsB4_Campo_32a_MontoParameter, lsB4_Campo_50k_CuentaParameter, lsB4_Campo_50k_NombreParameter, lsB4_Campo_50_Nom_CalleParameter, lsB4_Campo_50_Num_EdiParameter, lsB4_Campo_50_Cod_PosParameter, lsB4_Campo_50_Ubi_CdParameter, lsB4_Campo_50_regionParameter, lsB4_Campo_50_cod_paisParameter, lsB4_Campo_53d_Opt1Parameter, lsB4_Campo_53d_Opt2Parameter, lsB4_Campo_53d_NombreParameter, lsB4_Campo_56d_Opt1Parameter, lsB4_Campo_56d_Opt2Parameter, lsB4_Campo_56d_Desc1Parameter, lsB4_Campo_56d_NomCalleParameter, lsB4_Campo_56d_Num_EdiParameter, lsB4_Campo_56d_Cod_PosParameter, lsB4_Campo_56d_Ubi_CdParameter, lsB4_Campo_56d_RegionParameter, lsB4_Campo_56d_cod_paisParameter, lsB4_Campo_56d_AdrlineParameter, lsB4_Campo_57d_Opt1Parameter, lsB4_Campo_57d_Opt2Parameter, lsB4_Campo_57d_Desc1Parameter, lsB4_Campo_57d_NomCalleParameter, lsB4_Campo_57d_Num_EdiParameter, lsB4_Campo_57d_Cod_PosParameter, lsB4_Campo_57d_Ubi_CdParameter, lsB4_Campo_57d_RegionParameter, lsB4_Campo_57d_cod_paisParameter, lsB4_Campo_57d_AdrlineParameter, lsB4_Campo_59_FillerParameter, lsB4_Campo_59_Cta_BenefParameter, lsB4_Campo_59_NombreParameter, lsB4_Campo_59_Nom_CalleParameter, lsB4_Campo_59_Num_EdiParameter, lsB4_Campo_59_Cod_PosParameter, lsB4_Campo_59_Ubi_CdParameter, lsB4_Campo_59_regionParameter, lsB4_Campo_59_cod_paisParameter, lsB4_Campo_57_conceptoParameter);
        }
    }
}
